Importing, Creating and printing the array.

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


Printing the version of numpy.

In [2]:
print(np.__version__)

1.25.2


Printing the type of array created using numpy.

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Creating Dimensions.

In [4]:
import numpy as np

arr = np.array([1,2,3,4,5], ndmin = 5)

print(arr)
print(type(arr))
print(arr.ndim)

[[[[[1 2 3 4 5]]]]]
<class 'numpy.ndarray'>
5


### Objective: To create a one, two, three dimension matrix using elements.

In [5]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1,2,3,4,5], [1,2,3,4,5]])
# d = np.array([[1.2.3.4.5]. [1,2,3,4,5]],[[1,2,3,4,5],[1,2,3,4,5]]) Learn to make three dimensional using 2 two dimensional arrays.

print(a.ndim)
print(b.ndim)
print(c.ndim)
# print(d.ndim)

0
1
2


Access Array Element.

In [6]:
import numpy as np

arr = [1,2,3,4,5]
print(arr)
print(arr[0])

[1, 2, 3, 4, 5]
1


Accessing the second element.

In [7]:
import numpy as np

arr = [1, 2, 3, 4, 5]

print(arr)
print(arr[1])
print(arr[2])

print("Now adding the first and second element")

print(arr[0] + arr[1])

[1, 2, 3, 4, 5]
2
3
Now adding the first and second element
3


In [8]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print("5th element on 1st row: ", arr[0, 4])

print("3rd element on 2nd row: ", arr[1][2])

5th element on 1st row:  5
3rd element on 2nd row:  8


### Analyse this:

In [9]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2]) 

6


### Changing numpy datatype.
From float to int, 
From int to float

In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(f"Printing arr: {arr}")
print(arr.dtype)
print(f"Printing arr type: {arr.dtype}")

new_arr = arr.astype("f") # To change the data type of an existing array is to make a copy of the array with the astype() method.

print(new_arr)
print(new_arr.dtype)

Printing arr: [1 2 3 4 5]
int32
Printing arr type: int32
[1. 2. 3. 4. 5.]
float32
